Adjust references to composer.json and composer.lock because they are in the laravel directory.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -67,10 +67,10 @@ RTVS_URL="http://php-runtime-version-selector${RTVS_URL:-}.herokuapp.com"
 
 cd $BUILD_DIR
 
-if [[ -s "composer.json" ]]; then
-    cat composer.json | python -mjson.tool &> /dev/null || error "Could not parse composer.json; make sure it's valid!"
+if [[ -s "laravel/composer.json" ]]; then
+    cat laravel/composer.json | python -mjson.tool &> /dev/null || error "Could not parse composer.json; make sure it's valid!"
 else
-    if [[ ! -f "composer.json" ]]; then
+    if [[ ! -f "laravel/composer.json" ]]; then
         warning 'No composer.json found.
 Using index.php to declare PHP applications is considered legacy
 functionality and may lead to unexpected behavior.'
@@ -78,7 +78,7 @@ functionality and may lead to unexpected behavior.'
         notice 'Your composer.json is completely empty.
 Please change its contents to at least "{}" so it is valid JSON.'
     fi
-    echo "{}" > composer.json
+    echo "{}" > laravel/composer.json
 fi
 
 mkdir -p .heroku/php
@@ -95,21 +95,21 @@ else
 fi
 engine="php"
 engine_r="php -r"
-if [[ -f "composer.json" ]]; then
-    if [[ ! -f "composer.lock" ]]; then
-        cat composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your composer.json has dependencies, but no composer.lock
+if [[ -f "laravel/composer.json" ]]; then
+    if [[ ! -f "laravel/composer.lock" ]]; then
+        cat laravel/composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your composer.json has dependencies, but no composer.lock
 was found, check it into your repository alongside composer.json!"
     fi
-    
+
     solver_payload=$(echo -n "$runtimes" | python -c '
 import sys, json
 ret = {}
 ret["packages"] = sys.stdin.read().splitlines()
-c_json = dict(json.load(open("composer.json"))) # wrap in dict() to prevent simple errors with {} vs []
+c_json = dict(json.load(open("laravel/composer.json"))) # wrap in dict() to prevent simple errors with {} vs []
 ret["json"] = {k: c_json.get(k, None) for k in ["minimum-stability", "prefer-stable"]}
 ret["json"]["platform"] = {k: dict(c_json.get("require", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
 try:
-    c_lock = json.load(open("composer.lock"))
+    c_lock = json.load(open("laravel/composer.lock"))
     ret["lock"] = {k: c_lock.get(k, None) for k in ["minimum-stability", "prefer-stable", "stability-flags"]}
     ret["lock"]["platform"] = {k: dict(c_lock.get("platform", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
 except IOError:
@@ -151,7 +151,7 @@ will be removed soon. Please upgrade to cedar-14 to continue to
 use HHVM and get access to new releases. For more information,
 see https://devcenter.heroku.com/articles/cedar-14-migration"
                 fi
-                if [[ -f "composer.lock" ]] && python -c 'import sys, json; print sys.exit(any(key.count("hhvm") for key in json.load(open("composer.lock")).get("platform", {})))' 2> /dev/null; then
+                if [[ -f "laravel/composer.lock" ]] && python -c 'import sys, json; print sys.exit(any(key.count("hhvm") for key in json.load(open("laravel/composer.lock")).get("platform", {})))' 2> /dev/null; then
                     warning_inline "Support for requiring HHVM in 'composer.json' but not in
 'composer.lock' is deprecated and will be removed soon. Please
 update 'composer.lock' to contain the requirement. If you do not
@@ -225,24 +225,24 @@ echo $NGINX_VERSION > $BUILD_DIR/.heroku/php/.versions/nginx/nginx
 # handle extensions for PHP
 if [[ "${PHP_VERSION}" ]]; then
     status "Installing PHP extensions..."
-    
+
     php() {
         # the newrelic extension logs to stderr which pollutes our build output on each invocation of PHP, the daemon it launches will prevent the build from finishing, and each call to PHP would be logged to NR as non-web traffic, so we disable it for the duration of this build
         `which php` -dnewrelic.enabled=0 -dnewrelic.loglevel=error -dnewrelic.daemon.dont_launch=3 -dnewrelic.daemon.loglevel=error "$@"
     }
-    
+
     exts=()
-    if [[ -f "composer.lock" ]]; then
-        exts=($(cat composer.lock | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
-        ext_source="composer.lock"
+    if [[ -f "laravel/composer.lock" ]]; then
+        exts=($(cat laravel/composer.lock | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
+        ext_source="laravel/composer.lock"
     else
-        exts=($(cat composer.json | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
-        ext_source="composer.json"
+        exts=($(cat laravel/composer.json | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
+        ext_source="laravel/composer.json"
     fi
     for ext in "${!exts[@]}"; do # loop over keys in case the array is empty or else it'll error out
         install_ext "${exts[$ext]}" $ext_source
     done
-    
+
     # special treatment for New Relic; we enable it if we detect a license key for it
     install_newrelic_ext
 
@@ -319,7 +319,7 @@ composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction |
 composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires 'heroku/heroku-buildpack-php'.
 This package may only be used as a dependency in 'require-dev'!"
 
-if cat composer.json | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
+if cat laravel/composer.json | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
     status "Running 'composer compile'..."
     composer run-script --no-dev --no-interaction compile | indent
 fi
@@ -333,7 +333,7 @@ shopt -u dotglob # we don't want .git, .gitignore et al
 composer_vendordir=$(composer config vendor-dir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
 composer_bindir=$(composer config bin-dir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
 # figure out the package dir name to write to and copy to it
-hbpdir="$composer_vendordir/$(cat $BP_DIR/composer.json | python -c 'import sys, json; print json.load(sys.stdin)["name"]')"
+hbpdir="$composer_vendordir/$(cat $BP_DIR/laravel/composer.json | python -c 'import sys, json; print json.load(sys.stdin)["name"]')"
 mkdir -p "$BUILD_DIR/$hbpdir"
 cp -r "$BP_DIR"/* "$BUILD_DIR/$hbpdir/"
 # make bin dir, just in case
@@ -341,7 +341,7 @@ mkdir -p "$BUILD_DIR/$composer_bindir"
 # figure out shortest relative path from vendor/heroku/heroku-buildpack-php to vendor/bin (or whatever the bin dir is)
 relbin=$(python -c "import os.path; print os.path.relpath('$hbpdir', '$composer_bindir')")
 # collect bin names from composer.json
-relbins=$(cat $BP_DIR/composer.json | python -c 'from __future__ import print_function; import sys, json; { print(sys.argv[1]+"/"+bin) for bin in json.load(sys.stdin)["bin"] }' $relbin)
+relbins=$(cat $BP_DIR/laravel/composer.json | python -c 'from __future__ import print_function; import sys, json; { print(sys.argv[1]+"/"+bin) for bin in json.load(sys.stdin)["bin"] }' $relbin)
 # link to bins
 cd $BUILD_DIR/$composer_bindir
 ln -s $relbins .
diff --git a/bin/heroku-hhvm-apache2 b/bin/heroku-hhvm-apache2
--- a/bin/heroku-hhvm-apache2
+++ b/bin/heroku-hhvm-apache2
@@ -198,8 +198,8 @@ composer() {
         hhvm $composer_bin "$@"
     fi
 }
-COMPOSER_VENDOR_DIR=$(composer config vendor-dir 2> /dev/null | tail -n 1) && export COMPOSER_VENDOR_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
-COMPOSER_BIN_DIR=$(composer config bin-dir 2> /dev/null | tail -n 1) && export COMPOSER_BIN_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
+COMPOSER_VENDOR_DIR=laravel/$(cd laravel; composer config vendor-dir 2> /dev/null | tail -n 1) && export COMPOSER_VENDOR_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
+COMPOSER_BIN_DIR=laravel/$(cd laravel; composer config bin-dir 2> /dev/null | tail -n 1) && export COMPOSER_BIN_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
 
 if [[ "$#" == "1" ]]; then
     DOCUMENT_ROOT="$HEROKU_APP_DIR/$1"
@@ -257,10 +257,10 @@ if [[ -z ${WEB_CONCURRENCY:-} ]]; then
     fi
 
     # determine number of HHVM threads to run
-    read WEB_CONCURRENCY php_memory_limit <<<$(hhvm "${php_configs[@]}" $(composer config vendor-dir 2> /dev/null | tail -n 1)/heroku/heroku-buildpack-php/bin/util/autotune.php "$ram") # tail, as composer echos outdated version warnings to STDOUT
+    read WEB_CONCURRENCY php_memory_limit <<<$(hhvm "${php_configs[@]}" $(cd laravel; composer config vendor-dir 2> /dev/null | tail -n 1)/heroku/heroku-buildpack-php/bin/util/autotune.php "$ram") # tail, as composer echos outdated version warnings to STDOUT
     [[ $WEB_CONCURRENCY -lt 1 ]] && WEB_CONCURRENCY=1
     export WEB_CONCURRENCY
-    
+
     echo "${WEB_CONCURRENCY} threads at ${php_memory_limit}B memory limit." >&2
 else
     echo "Using WEB_CONCURRENCY=${WEB_CONCURRENCY} threads." >&2
diff --git a/bin/heroku-php-nginx b/bin/heroku-php-nginx
--- a/bin/heroku-php-nginx
+++ b/bin/heroku-php-nginx
@@ -62,7 +62,7 @@ Options:
                           directives (globals are read from the system's default
                           Nginx configuration files).
                           [default: \$COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/nginx/heroku.conf.php]
-  -F <php-fpm.inc.conf>   The path to the configuration file to include at the  
+  -F <php-fpm.inc.conf>   The path to the configuration file to include at the
                           end of php-fpm.conf (see option -f below), in the
                           '[www]' pool section. Recommended approach when
                           customizing PHP-FPM's configuration in most cases,
@@ -215,8 +215,8 @@ composer() {
         php $composer_bin "$@"
     fi
 }
-COMPOSER_VENDOR_DIR=$(composer config vendor-dir 2> /dev/null | tail -n 1) && export COMPOSER_VENDOR_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
-COMPOSER_BIN_DIR=$(composer config bin-dir 2> /dev/null | tail -n 1) && export COMPOSER_BIN_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
+COMPOSER_VENDOR_DIR=laravel/$(cd laravel; composer config vendor-dir 2> /dev/null | tail -n 1) && export COMPOSER_VENDOR_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
+COMPOSER_BIN_DIR=laravel/$(cd laravel; composer config bin-dir 2> /dev/null | tail -n 1) && export COMPOSER_BIN_DIR || { echo "Unable to determine Composer vendor-dir setting; is 'composer' executable on path or 'composer.phar' in current working directory?" >&2; exit 1; } # tail, as composer echos outdated version warnings to STDOUT; export after the assignment or exit status will that be of 'export
 
 if [[ "$#" == "1" ]]; then
     DOCUMENT_ROOT="$HEROKU_APP_DIR/$1"
@@ -277,10 +277,10 @@ if [[ -z ${WEB_CONCURRENCY:-} ]]; then
     fi
 
     # determine number of FPM processes to run
-    read WEB_CONCURRENCY php_memory_limit <<<$(php -c "$php_config" $(composer config vendor-dir 2> /dev/null | tail -n 1)/heroku/heroku-buildpack-php/bin/util/autotune.php -y "$fpm_config" -t "$DOCUMENT_ROOT" "$ram") # tail, as composer echos outdated version warnings to STDOUT
+    read WEB_CONCURRENCY php_memory_limit <<<$(php -c "$php_config" $(cd laravel; composer config vendor-dir 2> /dev/null | tail -n 1)/heroku/heroku-buildpack-php/bin/util/autotune.php -y "$fpm_config" -t "$DOCUMENT_ROOT" "$ram") # tail, as composer echos outdated version warnings to STDOUT
     [[ $WEB_CONCURRENCY -lt 1 ]] && WEB_CONCURRENCY=1
     export WEB_CONCURRENCY
-    
+
     echo "${WEB_CONCURRENCY} processes at ${php_memory_limit}B memory limit." >&2
 else
     echo "Using WEB_CONCURRENCY=${WEB_CONCURRENCY} processes." >&2
